// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NameGate.Database;

#nullable disable

namespace NameGate.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20240118154329_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("NameGate.Database.Entities.DomainStatisticsEntity", b =>
                {
                    b.Property<string>("Domain")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AllowedCount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("BlockedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Domain");

                    b.ToTable("DomainStatistics");
                });

            modelBuilder.Entity("NameGate.Database.Entities.IpStatisticsEntity", b =>
                {
                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AllowedCount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("BlockedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("IpAddress");

                    b.ToTable("IpStatistics");
                });

            modelBuilder.Entity("NameGate.Database.Entities.WhiteListEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainGlob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WhiteListEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
